import Head from 'next/head';
import { FlexContainer, PageContainer } from '../../components/common';
import StoreLayout from '../../components/layouts/store';

const DetailedCollection = () => {
  return (
    <div>
      <Head>
        <title>AVO NFT - Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FlexContainer>
        <PageContainer>Collections</PageContainer>
      </FlexContainer>
    </div>
  );
};

DetailedCollection.PageLayout = StoreLayout;

export default DetailedCollection;
