export enum AdminRoute {
  MAIN = '/admin/',
  LOGIN = '/admin/login',
  NFT = '/admin/NFT',
  COLLECTIONS = '/admin/collections',
  BIDS = '/admin/bids',
  USERS = '/admin/users',
  AUTHORS = '/admin/authors',
  WALLETS = '/admin/wallets',
  CATEGORIES = '/admin/categories',
  BILLING = '/admin/billing',
  TOKEN = '/admin/token',
  FAQS = '/admin/faqs',
  REPORTS = '/admin/reports',
  NOTIFICATIONS = '/admin/notifications',
}
