import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import styled from 'styled-components';
import { devices } from '../../common/constants';
import { getQueryParams } from '../../common/helpers/manageQueryParams.helper';
import {
  CREATOR_ITEMS,
  LIKE_ITEMS,
  PRICE_ITEMS,
  TYPE_ITEMS,
} from '../../components/catalog/constants';
import FilterBar from '../../components/catalog/FilterBar';
import {
  convertQueryParams,
  onLocationChange,
} from '../../components/catalog/helpers';
import { TFilterOption } from '../../components/catalog/types';
import { FlexContainer, PageContainer } from '../../components/common';
import BidGrid from '../../components/common/components/BidGrid';
import StoreLayout from '../../components/layouts/store';
import { useAppDispatch, useAppSelector } from '../../redux/hooks';
import { fetchCategories } from '../../redux/slicers/discoverSlicer/discoverSlicer';
import { TDiscoverState } from '../../redux/slicers/discoverSlicer/types';
import SearchWithBadRequest from '../../components/common/components/SearchWithBadRequest/SearchWithBadRequest';

const Catalog = () => {
  const dispatch = useAppDispatch();
  const router = useRouter();
  const searchName = router.query.name;

  const [queryParams, setQueryParams] = useState<string>();
  const { categories, bids, nfts, loading, priceRange } =
    useAppSelector<TDiscoverState>((state) => state.discover);

  const handleLocationChange = onLocationChange(dispatch);

  const onCategoryChange = () => {
    const queryParams = convertQueryParams(
      getQueryParams(window.location.search),
    );
    console.log('queryParams=', queryParams);
    setQueryParams(JSON.stringify(queryParams));
  };

  // const handlePageChange = (page: number) => {
  //   pushQueryParams([{ name: 'page', value: page }]);
  // };

  const categoryOptions: TFilterOption[] = categories.map((category) => ({
    id: category._id,
    name: category.name,
    url: category._id,
  }));

  useEffect(() => {
    localStorage.removeItem('location');
    window.addEventListener('locationChange', () => {
      handleLocationChange();
      onCategoryChange();
    });

    // setTimeout(() => {
    //   setPriceRange({
    //     minPrice: 0,
    //     maxPrice: 1000,
    //   });
    // });

    (async () => {
      await dispatch(fetchCategories());
      await handleLocationChange();
      onCategoryChange();
    })();

    return () => {
      window.removeEventListener('locationChange', handleLocationChange);
    };
  }, []);

  return (
    <div>
      <Head>
        <title>AVO NFT - Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FlexContainer>
        {!!bids.length || !!nfts.length ? (
          <PageContainer>
            <ContentHeading>
              <ContentTitle>{searchName}</ContentTitle>
            </ContentHeading>
            <ContentWrapper style={{ paddingTop: '60px' }}>
              <FilterBar
                types={TYPE_ITEMS}
                categories={categoryOptions}
                likes={LIKE_ITEMS}
                prices={PRICE_ITEMS}
                isVerifieds={CREATOR_ITEMS}
                priceRange={priceRange}
              />
              {loading && '...loading'}
              {!loading && (
                <BidGrid items={[...bids, ...nfts]} elemPerRow={3} />
              )}
            </ContentWrapper>
          </PageContainer>
        ) : (
          <SearchWithBadRequest />
        )}
      </FlexContainer>
    </div>
  );
};

const ContentWrapper = styled.div`
  display: flex;
  gap: 100px;
  padding-top: 128px;
  width: 100%;
  padding-bottom: 112px;

  @media (${devices.mobile}) {
    padding-top: 80px;
    flex-direction: column;
  }
`;

const ContentHeading = styled.div`
  display: flex;
  flex-direction: column;
  gap: 16px;
  width: 100%;
`;

const ContentTitle = styled.h1`
  font-family: 'Nasalization';
  font-weight: 400;
  font-size: 48px;
  line-height: 64px;
  letter-spacing: -0.02em;
  color: #ffffff;
  max-width: 455px;
  margin: 40px 0 0;
`;

Catalog.PageLayout = StoreLayout;

export default Catalog;
