import Head from 'next/head';
import styled from 'styled-components';
import { FlexContainer } from '../components/common';
import { ButtonSize } from '../components/common/enums/buttonSize.enum';
import { ButtonType } from '../components/common/enums/buttonType.enum';
import Bids from '../components/home-page/bids';
import CreatorNetwork from '../components/home-page/CreatorNetwork';
import HotBids from '../components/home-page/HotBids';
import HotCollections from '../components/home-page/HotCollections';
import Popular from '../components/home-page/Popular';
import StoreLayout from '../components/layouts/store';
import Button from '../components/ui-kit/Button';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FlexContainer>
        <MainContainer>
          <PageDesc>Create, explore, & collect digital art NFTs.</PageDesc>
          <PageTitle>The new creative economy.</PageTitle>
          <Button type={ButtonType.Primary} size={ButtonSize.Large}>
            Start your search
          </Button>
          <CreatorNetwork />
          <Bids />
        </MainContainer>
      </FlexContainer>
      <Popular />
      <HotBids />
      <HotCollections />
    </div>
  );
};

const MainContainer = styled.main`
  padding-top: 81px;
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100%;
`;

const PageDesc = styled.div`
  width: 100%;
  text-align: center;
  font-size: 12px;
  line-height: 12px;
  font-weight: bold;
  font-family: 'Poppins', sans-serif;
  color: rgba(119, 126, 144, 1);
  padding-top: 128px;
  text-transform: uppercase;
`;

const PageTitle = styled.h1`
  width: 100%;
  text-align: center;
  font-size: 40px;
  line-height: 48px;
  font-weight: bold;
  font-family: 'DM Sans', sans-serif;
  color: rgba(35, 38, 47, 1);
  margin: 0;
  padding-top: 8px;
  margin-bottom: 24px;
`;

Home.PageLayout = StoreLayout;

export default Home;
