import Head from 'next/head';
import styled from 'styled-components';
import { useAdaptiveSlider } from '../common/hooks/useAdaptiveSlider';
import { FlexContainer } from '../components/common';
import CreatorNetwork from '../components/home-page/CreatorNetwork';
import Discover from '../components/home-page/Discover';
import HotBids from '../components/home-page/HotBids';
import HotCollections from '../components/home-page/HotCollections';
import Popular from '../components/home-page/Popular';
import StoreLayout from '../components/layouts/store';
import { ReactSlick } from '../components/ui-kit';
import { useAppSelector } from '../redux/hooks';
import { TBidsState } from '../redux/slicers/bidsSlicer/types';
import { IBid } from '../swagger';

const Home = () => {
  //TODO: remove Mocks

  const { bids } = useAppSelector<TBidsState>((state) => state.bids);

  const { screenSize } = useAdaptiveSlider(1);

  const getHotBit = (bids: IBid[]) =>
    bids?.map((bid) => <CreatorNetwork key={bid._id} bid={bid} />);

  return (
    <div>
      <Head>
        <title>AVO NFT - create single collectible</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FlexContainer>
        <StyledPageContainer>
          <ReactSlick screenSize={screenSize} slidesPerRow={1}>
            {getHotBit(bids)}
          </ReactSlick>
          {/* <Bids /> */}
        </StyledPageContainer>
      </FlexContainer>
      <Popular />
      <HotBids />
      <HotCollections />
      <Discover />
    </div>
  );
};

const StyledPageContainer = styled.main`
  padding-top: 81px;
  width: 100%;
`;

Home.PageLayout = StoreLayout;

export default Home;
